# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Fix permissions
        run: |
          sudo chown -R $USER:$USER /home/ubuntu/frontend/_work
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Clean npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: npm install

      - name: Stop existing PM2 process
        run: pm2 stop "react-app" || true

      - name: Delete existing PM2 process
        run: pm2 delete "react-app" || true

      - name: Start with PM2
        run: pm2 start npm --name "react-app" -- start

      - name: Save PM2 configuration
        run: pm2 save --force
